language: python

services:
  - postgresql

python:
  - "2.7"
  - "3.4"

env:
  - RUN_ENV=test
  - DB_NAME=testing

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database testing" -U postgres
  - source .env.${RUN_ENV}

script: 
  - nosetests

branches:
  only:
    - master
